### ISSUE TITLE
Feature Request: Support for async Task<T> Return Types in Subscriber Classes

### ISSUE THREAD

**Issue by KonstantinHamm** [MarcinZiabek/message-router#4]
I would like to request the addition of support for return types of async Task<T> in the subscriber classes of the "MessageRouter" project. This enhancement would enable the use of asynchronous methods within the subscriber methods, allowing for await functionality.

**Comment by MarcinZiabek** [comment]
Thank you for reaching out and for your interest in this library 😄

I regret to inform you that I cannot provide sufficient support at this time, as I am fully dedicated to the QuestPDF project. Unfortunately, Message.Router has not seen significant adoption. However, I am very open to any pull requests. If anyone updates the library to meet new .NET standards or adds new features, I will be happy to publish a new version on NuGet.

If you are an active user of this library and do not wish to submit a pull request, please feel free to fork the project.

I hope you understand that I want to be honest about my availability and the level of support for Message.Router. Thank you for your understanding, and I wish you a wonderful day!

**Comment by KonstantinHamm** [comment]
Hello Marcin,
Thank you for your quick response! From the perspective of Message.Router, it's of course unfortunate to hear. I am a big fan of this library. I will see if I might be able to spare some time to implement this extension. In the meantime, I wish you much success with your projects!
